---
title: "DataTypesAtomicVectors_2024_02_06.Rmd"
author: "Emily Dombrowski"
date: "2024-02-06"
output: html_document
---

```{r}
# create atomic vector (avoid this)
z <- vector(mode="numeric", length=0)
print(z)

# add element ot it
z <- c(z,5)
head(z)
# this "dynamic sizing" is very slow

# create a vector of 100 0s
z <- rep(0,100)
head(z)

# better to start with NAs
z<- rep(NA,100)
typeof(z)
z[1] <- "Washington"
head(z)
typeof(z)
# coerced into character
# Start with NAs then add on
```
# Efficiently create a large vector with names
```{r}
my_vector <- runif(100)
my_names <- paste("Species",
                  seq(1:length(my_vector)),
                  sep="")
head(my_names)
names(my_vector) <- my_names
head(my_vector)
```
# using the repeat function
```{r}
rep(0.5,6)
rep(x=0.5,times=6) # give input names
rep(times=6, x=0.5) # order not important if names specified
my_vec <- c(1,2,3)
rep(x=my_vec, times=2)
rep(x=my_vec, each=2)
rep(x=my_vec, times=my_vec) # what would this do
# each element is matched up to the number it is specified
rep(x=my_vec, each=my_vec)
# why? we get error message
```

# Using seq vector
```{r}
seq(from=2, to=4)
2:4
# generates the same thing. Common in R coding

seq(from=2, to=4, by=0.5)
# increment up by 0.5
x <- seq(from=2, to=4, length=7)
# r divides it for us
my_vec <- seq(1:length(x))
my_vec
seq_along(x)
seq_len(5)

# a couple of ways to generate sequences
```

```{r}
runif(5)
runif(n=3, min=100, max=103)
rnorm(6)
rnorm(n=6, mean=100, sd=30)
```

# Explore distributions by sampling and plotting
```{r}
library(ggplot2)
z <- runif(1000)
qplot(z) # error message
m.hist(z)
```
# using sample function
```{r}
long_vec <- seq_len(10)
long_vec
sample(long_vec) # with no other parameters, it reorders the data
sample(long_vec, size=3) # specify a number, sampling without replacement
sample(long_vec, size=16) # too large
sample(long_vec, size =16, replace = TRUE)
# numbers are randombly drawn but can be replaced

my_weights <- c(rep(20,5),rep(100,5))
# set of non-sero positive weights (integers or real)
my_weights
sample(x=long_vec, replace=TRUE, prob=my_weights)
# weights are proportionally related to values
# weighted toward to back end of the list
sample(x=long_vec, replace=FALSE, prob=my_weights)
# all numbers represented but the higher numbers come first

sample(x=long_vec, replace = TRUE, prob=long_vec)
# assigns weights based on data. Fewer low numbers on list
```

# subsetting atomic vectors
```{r}
z <- c(3.1, 9.2, 1.3, 0.4, 7.5)

# positive index values
z[c(2,3)]
# pulls out second and third values on list
z[c(2,2,3,3)]

# negative index values to exclude elements
z[-c(2,3)]

# create a vector of logical elements to select
# based on values

z < 3
# generates boolean based on properties of 3
z[z<3]
# gives back elements that repond to the subset

tester <- z<3
print(tester)
z[tester]
```
# Which
```{r}
which(x<3)

# use length to get positions reletive to start
# and end of vector
# select everthing but last two elements

z[-(length(z):(length(z)-1))]

# subset using named vector elements
names(z) <- letters[1:5]
z[c("b","c")]

# relational operators in R
# < less than
# > greater than
# <= less than or greater to
# >= greater than or equal to
# == equal to

# ! not
# & and (vector)
# | or (vector)
# xor(vec_a,vec_b) one or the other but not both
# && and (only for the first element)
# || or (only for the first element)

x <- 1:5
y <- c(1:3,7,7)


x==2 # boolean evaluating output
x!=2 # only second elements are false

x==1
x==7
y == 7
x == 1 & y == 7 # vector of all falses...there are never
# two trues 

x == 1 | y == 7
# we get two instances of true
x == 3 | y == 3
# single two in third slot

xor( x == 3, y == 3)
# one of them has to be true BUT NOT the other. Both can't be trye
x == 3 && y == 3
```

# relational operators in R
< less than
> greater than
<= less than or greater to
>= greater than or equal to
== equal to

# subscripting with missing values
```{r}
set.seed(90)
z <- runif(10)
print(z)

z < 0.5 # create a logical vector
z[z < 0.5] # pulls out numbers less than 5 in z
which(z < 0.5) # gives us positions with those conditions
z[which(z<0.5)]

# which behaves differently with NAs in the data
zD <- c(z,NA,NA)
zD[zD < 0.5] # na values carried with it
zD[which(zD < 0.5)] # drops NA values
```