---
title: "hw5.Rmd"
author: "Emily Dombrowski"
date: "2024-02-14"
output: html_document
---

# Question 1
Assign to the variable 'n_dims' a single random integer between 3 and 10.

```{r}
# generate random integer between 3 and 10
n_dims <- sample(3:10, size = 1)

# generate vector from 1 to n_dims^2
vec <- (1:n_dims^2)
print(vec)

# reshuffle vector
vec <- sample(vec)
length(vec) # length = 16, therefore 4 x 4 matrix
# even better: populate with n_dims in order to avoid errors

# turn vector into a square matrix
m <- matrix(data = vec, nrow = n_dims)
print(m)

# transpose matrix
m <- t(m)
print(m)
  # order of rows and columns have changed

# calculate the sum and the mean of the elements in the first row and then the last row.
sum_r1 <- sum(m[1,])
mean_r1 <- mean(m[1,])

sum_r4 <- sum(m[4,])
mean_r4 <- mean(m[4,])

# read about the eigen() function and use it on your matrix
# Computes eigenvalues and eigenvectors of numeric (double, integer, logical) or complex matrices.
# an eigen vector is a vector associated with a set of linear equations
# an eigen value is the factor by which an eigen vector is squished
# these functions can only be used with square matrices

eigen_m <- eigen(m)
print(eigen_m)

# look carefully at the elements of $values and $vectors in the output. What kind of numbers are these?
# $values numbers are unreal numbers (they end with i)
# $vectors are also small unreal numbers

typeof(eigen_m$values)
# outputs complex numbers
typeof(eigen_m$vectors)
# again, outputs complex
```
# Question 2. 
Create a list with the following named elements:
```{r}
# my_matrix, which is a 4 x 4 matrix filled with random uniform values
random_nums <- runif(16)
my_matrix <- matrix(data = random_nums, nrow = 4)

# my_logical which is a 100-element vector of TRUE or FALSE values. Do this efficiently by setting up a vector of random values and then applying an inequality to it.
my_vec <- runif(100)
my_logical <- my_vec > runif(1)

# my_letters, which is a 26-element vector of all the lower-case letters in random order.
my_letters <- sample(letters[1:26])

# Then, complete the following steps:
# create a new list, which has the element[2,2] from the matrix, the second element of the logical vector, and the second element of the letters vector.
new_list <- list(my_matrix[2,2], my_logical[2], my_letters[2])

# use the typeof() function to confirm the underlying data types of each component in this list
typeof(new_list)
str(new_list)
# outputs type is list. str() gives number, logical, and character

# combine the underlying elements from the new list into a single atomic vector with the c() function.
vec_list <- c(my_matrix[2,2], my_logical[2], my_letters[2])

# what is the data type of this vector?
typeof(vec_list)
str(vec_list)
# r coerces vector into characters
```

# Question 3
Create a data frame with the two variables (= columns) and 26 cases (= rows) below:
```{r}
# call the first variable my_unis and fill it with 26 random uniform values from 0 to 10
my_unis <- runif(26, 0, 10)

# call the second variable my_letters and fill it with 26 capital letters in random order.
my_letters <- sample(LETTERS[1:26])

dat <- data.frame(my_unis, my_letters)
print(dat)
# creates data frame with two variables

# for the first variable, use a single line of code in R to select 4 random rows and replace the numerical values in those rows with NA.
rows <- sample(length(my_unis), size = 4)
dat[rows,1] <- NA

# for the first variable, write a single line of R code to identify which rows have the missing values.
which(is.na(dat$my_unis))

# re-order the entire data frame to arrange the second variable in alphabetical order
dat <- dat[order(dat$my_letters),]
print(dat)

# calculate the column mean for the first variable.
mean(dat$my_unis, na.rm = TRUE)
```