---
title: "Computational Biology Portfolio"
author: "Emily Dombrowski"
date: "Created 2024-1-24"
output: 
  html_document: 
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(exho=TRUE)
```

# Welcome
Hello, welcome to my portfolio for my assignments for Computational Biology (BIOL 6100) Spring 2024.

This is the link [Homework #3](hw3.html). This homework assignment evaluates regular expressions. 

This is the link to [Homework #4](hw4.html). This homework explores the use of atomic vectors.

This is the link to [Homework #5](hw5.html). This homework evaluates matrices, lists, and working with data structures. 

This is the link to [Homework #6](hx6.html). This homework looks at simulating data and distributions.

This is the link to [Homework #7](hw7.html). This homework simulates data and uses statistical tests and boxplots to evaluate hypothesized relationships.

This is the link to [Homework #8](hw8.html).This homework is focused on wrangling data using dplyr. 

This is the link to [Homework #9](hw9.html). This homework is replicating the process of creating functions in a back-end script with lots of documentation, and then concisely running the script in a few lines in a front-end script. It is demonstrated in a markdown format for easier viewing. 

This is the link to [Homework #10](hw10.html). This homework works with loops.

This is the link to [Homework #11](hw11.html), which uses the BaracudaR practices to do batch processing in R.

This is the link to [Homework #12](hw12.html). In this homework, I explore some plots that I've never made before in ggplot.